on:
    push:
        branches:
            - main

jobs:
    contrib-readme-job:
        runs-on: ubuntu-latest
        name: A job to automate contrib in readme
        permissions:
          contents: write
          pull-requests: write
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Contribute List
              uses: akhilmhdh/contributors-readme-action@v2.3.10
              with:
                  image_size: 75
                  use_username: true
                  columns_per_row: 5
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Wrap Contributors Section in Details Tag
              run: |
                cat > update_readme.py << 'EOF'
                import re

                def wrap_contributors_section():
                    with open('README.md', 'r') as f:
                        content = f.read()

                    # Pattern to identify and wrap the contributors section
                    pattern = r'(## Contributors\n\n)(.*?)(\n\n## |$)'
                    replacement = (
                        "## Contributors\n\n"
                        "<details>\n"
                        "  <summary>Click to see contributors</summary>\n\n"
                        "\\2\n"  # Preserve the dynamically generated list of contributors
                        "</details>\n\n"
                    )

                    # Replace the existing contributors section with the wrapped version
                    new_content = re.sub(pattern, replacement, content, flags=re.DOTALL)

                    with open('README.md', 'w') as f:
                        f.write(new_content)

                if __name__ == "__main__":
                    wrap_contributors_section()
                EOF
                python update_readme.py

            - name: Commit and Push Changes
              run: |
                git config --global user.name 'github-actions[bot]'
                git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                git add README.md
                git diff --staged --quiet || (git commit -m "Updated contributors section with toggle" && git push)
