name: PR Issue Checker
on:
  pull_request:
    types: [opened, edited]

jobs:
  check_pr_description:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check PR Description
        id: check_pr_description
        run: |
          # Get PR description
          PR_DESCRIPTION="${{ github.event.pull_request.body }}"

          PR_DESCRIPTION=$(echo "$PR_DESCRIPTION" | tr -d '\r' | tr -d '\n')

          if [[ -z "$PR_DESCRIPTION" ]]; then
            echo "PR description is missing."
            exit 1
          fi

          if ! echo "$PR_DESCRIPTION" | grep -Eq "(Fixes|Closes) #[0-9]+"; then
            echo "The PR description should include 'Fixes #<issue-number>' or 'Closes #<issue-number>' if addressing an issue."
            echo "##[error]Fixes #<issue-number> or Closes #<issue-number> must be included in the description."
            exit 1
          fi

          echo "PR description is valid."

      - name: All checks passed
        run: echo "All checks passed."
