name: Comment on Pull Request

on:
  pull_request:
    types: [opened, reopened]

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
            Hello world! :wave: Thank you for submitting your pull request! 🙌 We'll review it as soon as possible. 😊
