name: Auto Comment on PR Merge

on:
  pull_request:
    types: [opened, closed]

permissions:
  issues: write
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - name: Add Comment to Pull Request
      if: github.event.action == 'opened'
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
          -X POST \
          -H "Authorization: Bearer $PAT_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"body": "Thank you for submitting your pull request! 🙌 We'\''ll review it as soon as possible. 😊"}' \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments)
        
        cat response.json
        if [ "$RESPONSE" -ne 201 ]; then
          echo "Failed to add comment on PR opened"
          exit 1
        fi

    - name: Add Comment to Merged Pull Request
      if: github.event.action == 'closed' && github.event.pull_request.merged == true
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        RESPONSE=$(curl -s -o response.json -w "%{http_code}" \
          -X POST \
          -H "Authorization: Bearer $PAT_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          -d '{"body": "🎉 Your pull request has been successfully merged! 🎉 Thank you for your valuable contribution to our project. Your efforts are greatly appreciated. Feel free to reach out if you have any more contributions or if there'\''s anything else we can assist you with. Keep up the fantastic work! 🚀"}' \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments)
        
        cat response.json
        if [ "$RESPONSE" -ne 201 ]; then
          echo "Failed to add comment on PR merged"
          exit 1
        fi
